### ISSUE TITLE
Error on Example Application

### ISSUE THREAD

**Issue by raguay** [maxogden/menubar#106]
I am just trying to run the example before I make changes for my own needs. But, the example will not run. I am getting:

App threw an error when running [TypeError: Cannot read property 'getAppPath' of undefined]

Any ideas?

**Comment by maxogden** [comment]
im using node 4 on mac os, using these steps it works OK for me:

- cd example/
- rm -rf node_modules
- npm install
- npm start

can you give me steps to reproduce your error?

**Comment by raguay** [comment]
I followed the above sequence and it still crashes with this message:

Uncaught Exception:
TypeError: Cannot read property 'getAppPath' of undefined
    at create (/Users/raguay/Documents/QuiverMenubar/QuiverMate/node_modules/menubar/index.js:14:52)
    at Object.<anonymous> (/Users/raguay/Documents/QuiverMenubar/QuiverMate/main.js:3:10)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (/Users/raguay/Documents/QuiverMenubar/QuiverMate/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app/main.js:258:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)

I have node version 5.5.0 installed on the system. The Electron version is v0.36.7. I changed the directory names to match the app I'm making. That is the only thing I have changed.

**Comment by davidlashlee** [comment]
same problem for me. node 5.1, electron 0.4.1, OS X el capitan

I'm going to update my node version and try again.

``Uncaught Exception:
TypeError: Cannot read property 'getAppPath' of undefined
    at create (/Users/.../quicktimer/node_modules/menubar/index.js:14:52)
    at Object.<anonymous> (/Users/.../quicktimer/app.js:3:10)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app/main.js:258:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)``

**Comment by maxogden** [comment]
Weird, i'm unable to reproduce on Yosemite. The line causing the error is here: https://github.com/maxogden/menubar/blob/42c1c7d2ddb0c2219278e0033523dab3f3252489/index.js#L14

But there is no reason that `app` should be `undefined`, as it is required here: https://github.com/maxogden/menubar/blob/42c1c7d2ddb0c2219278e0033523dab3f3252489/index.js#L6

**Comment by davidlashlee** [comment]
Pretty sure this is electron related and not a menu bar issue. Will update with more info later today.

**Comment by davidlashlee** [comment]
https://github.com/atom/electron/issues/3708

this is what i think the issue is

**Comment by simonhochrein** [comment]
Try updating to electron-prebuilt@1.0.1
