### ISSUE TITLE
Build issue on Mac OS

### ISSUE THREAD

**Issue by tn** [maxogden/menubar#47]
Version of menubar: 2.0.17
CLI: `npm run build` in [electron-generator](https://github.com/sindresorhus/generator-electron)
Platform: Mac OS Yosemite

I get error message when I run builded app for Mac OS:
```
A JavaScript error occured in the browser process

Uncaught Exception:
TypeError: app.getAppPath is not a function
    at create (/Users/timurnurislamov/Code/tomatron/node_modules/menubar/index.js:14:33)
    at Object.<anonymous> (/Users/timurnurislamov/Code/tomatron/dist/Tomatron-darwin-x64/Tomatron.app/Contents/Resources/app.asar/index.js:3:10)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Object.<anonymous> (/Users/timurnurislamov/Code/tomatron/dist/Tomatron-darwin-x64/Tomatron.app/Contents/Resources/atom.asar/browser/lib/init.js:104:10)
    at Object.<anonymous> (/Users/timurnurislamov/Code/tomatron/dist/Tomatron-darwin-x64/Tomatron.app/Contents/Resources/atom.asar/browser/lib/init.js:106:4)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
```

You can see this `TypeError: app.getAppPath is not a function
    at create (/Users/timurnurislamov/Code/tomatron/node_modules/menubar/index.js:14:33)`

I need just some help. Thanks

**Comment by jenslind** [comment]
Yes, thats because `app.getAppPath` was first introduced in electron `v0.30.0`. What version do you use? The build script in menubars example uses `v0.26.0`, I will update it.

**Comment by tn** [comment]
@jenslind you right. Application work fine now. Thank you.

**Comment by jenslind** [comment]
Great!
